General inference procedure for ML4H models with applications to segmentations
broadinstitute/ml4h pull request #406
Opened 2020-11-11 14:18 UTC by mklarqvist

* Load a ML4H/Keras/TF model and make inference on batches of data.
* Compute segmentation masks and store on disk

No inference probabilities are stored in this application

2020-11-17 18:03 UTC, lucidtronix requested changes
Awesome work! Let's integrate this more in the ml4h package by using our arguments namespace and adding it the ml4h package.  Eventually we'll want to add all our inference recipes here.  Besides that little nits about logging and how to get the auxiliary files.

2020-11-17 18:03 UTC, lucidtronix commented on ml4h/applications/segmentation/mri_inference.py
> +# Command line helper for divide-and-conquer approach to inferring
Wrap this all in a function named `infer_pngs` or something

2020-11-17 19:30 UTC, lucidtronix commented on ml4h/applications/segmentation/mri_inference.py
> +                tensor = pad_or_crop_array_to_shape((224, 224, 1), dat[..., d])
Can this iterate over `args.tensor_maps_output` and use tm.shape?

2021-01-27 15:47 UTC, lucidtronix approved these changes
2 small changes and then good to merge, no need to bounce back!

2021-01-27 15:47 UTC, lucidtronix commented on ml4h/applications/jpp_inference_rv/infer_to_hd5_local.sh
> +	gcloud compute ssh $vm_base_name-${i} --command="cd /home/pdiachil;cd ml;git pull;git checkout pd_sf_blox;git pull;nohup bash /home/pdiachil/ml/scripts/infer_to_hd5.sh $i > /home/pdiachil/out_${i}.o
can we replace `pdiachil` with `${USER}`

2021-01-27 15:47 UTC, lucidtronix commented on ml4h/applications/jpp_inference_rv/infer_to_hd5_local.sh
> +	       --accelerator=type=nvidia-tesla-p4,count=1 &
p4 -> t4

2021-01-27 15:47 UTC, lucidtronix commented
@mklarqvist back to you

2021-01-27 16:10 UTC, merged

2021-01-27 16:12 UTC, paolodi commented on ml4h/applications/jpp_inference_rv/infer_to_hd5_local.sh
> +	gcloud compute instances attach-disk ${vm_base_name}-${i} --disk=${target_disk} --mode ro &
@mklarqvist thanks for fixing these as command line arguments!!!