ml4ht integration
broadinstitute/ml4h pull request #426
Opened 2021-02-10 19:50 UTC by ndiamant

Adds the ability to use `DataDescription` from https://github.com/broadinstitute/torch_ml4h as `TensorMap` in the model factory, and to use `TensorMap`s as `DataDescription`s in ml4ht data loaders.

2021-02-17 18:47 UTC, mklarqvist requested changes
Needs only improved documentation otherwise good. 👍

2021-02-17 18:47 UTC, mklarqvist commented on ml4h/ml4ht_integration/tensor_map.py
> +    def __init__(
We need a comment here with what this is and how to use it (including an example)

2021-02-17 18:47 UTC, mklarqvist commented on ml4h/ml4ht_integration/tensor_map.py
> +    Allows a DataDescription to be used in the model factory
We need to expand on this comment, including describing the parameters, an example, and examples of valid kwargs.

2021-04-01 12:06 UTC, mklarqvist approved these changes
👍

2021-04-23 18:44 UTC, lucidtronix approved these changes
LGTM!

2021-07-08 13:06 UTC, lucidtronix commented
I think this all got merged via #447,  @ndiamant feel free to reopen if I'm mistaken.

2021-07-08 13:06 UTC, closed without merging

2021-07-09 17:35 UTC, mklarqvist commented
🎉  @ndiamant