regplot update to return OLS summary statistics
broadinstitute/ml4h pull request #429
Opened 2021-02-18 21:33 UTC by mklarqvist

The returns OLS fit is very useful for retrieving correlations and other meaningful statistics

```
fit = regplot(y='area_legs',x='volume_legs',res_hue_limit=0.05,dataframe=df,destination='test.jpg')
fit.summary()
```

![test](https://user-images.githubusercontent.com/11334612/108424268-f1fa1200-7206-11eb-82c1-61a2de1124f7.jpg)

![Screen Shot 2021-02-18 at 4 32 32 PM](https://user-images.githubusercontent.com/11334612/108424253-edcdf480-7206-11eb-944b-9b57bd386327.png)

2021-02-18 23:25 UTC, ndiamant requested changes
A few nitpicks then ready

2021-02-18 23:25 UTC, ndiamant commented on ml4h/plots.py
> +    # residuals = pd.DataFrame({x:dataframe[x],y:res.resid})
left in on accident?

2021-02-18 23:25 UTC, ndiamant commented on ml4h/plots.py
> +        markers (tuple, optional): Tuple of chars controlling point types. Defalts to ["o", "o"].
which point sizes, points and outliers?

2021-02-18 23:48 UTC, mklarqvist commented
Good points. Updated

2021-02-20 00:10 UTC, ndiamant approved these changes

2021-02-20 00:10 UTC, merged