Perceiver
broadinstitute/ml4h pull request #523
Opened 2023-06-07 14:54 UTC by kaiyuanmifen

Perceiver + embedding based transformer

2023-06-07 21:13 UTC, lucidtronix requested changes
This is great @kaiyuanmifen !  I'm still reviewing the model blocks, but I did a pass just doing small changes. And we should look into why the tests are failing

2023-06-07 21:13 UTC, lucidtronix commented on ml4h/models/perceiver_blocks.py
> +    # )(latents + attention)
remove this or provide alternate control flow?

2023-06-09 16:39 UTC, lucidtronix commented
@kaiyuanmifen I think the serialization issue is because the custom classes you've added need to also be added into this function: `_get_custom_objects` line 304 of `model_factory.py` https://github.com/broadinstitute/ml4h/blob/Dianbo/ml4h/models/model_factory.py#L304

Can you try adding all the newly defined custom objects there and then seeing if serialization works.

2023-06-09 18:40 UTC, kaiyuanmifen commented
Dear Sam

Yes, there was a problem running the serializaiton of the new part and
save the model, which I have not solved. The training runs ok.

On Wed, Jun 7, 2023 at 5:14 PM Samuel Friedman ***@***.***>
wrote:

> I think the test is failing because the model serialization was commented
> out. Can you restore that and see if tests pass again?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/broadinstitute/ml4h/pull/523#issuecomment-1581522825>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHD5PICPWVU4AGDVAQOGTXTXKDVMRANCNFSM6AAAAAAY577JZQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-16 14:19 UTC, kaiyuanmifen commented
fixing saving and inference

2023-09-19 14:40 UTC, lucidtronix approved these changes

2023-09-19 15:07 UTC, merged